In [59]:
# import important libraries
import numpy as np
import pandas as pd
import seaborn as sns
import sklearn.utils
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
import imblearn
from imblearn.over_sampling import SMOTE
from sklearn.linear_model import LogisticRegression

In [60]:
# import dataset
df = pd.read_csv('data.world.csv')
df

C:\Users\Praise\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


Unnamed: 0  country  year  country_code        record     crop_land  \
0               0  Armenia  1992             1    AreaPerCap  1.402924e-01   
1               1  Armenia  1992             1     AreaTotHA  4.830000e+05   
2               2  Armenia  1992             1  BiocapPerCap  1.598044e-01   
3               3  Armenia  1992             1  BiocapTotGHA  5.501762e+05   
4               4  Armenia  1992             1  EFConsPerCap  3.875102e-01   
...           ...      ...   ...           ...           ...           ...   
72181       72181    World  2016          5001  BiocapTotGHA  3.984702e+09   
72182       72182    World  2016          5001  EFConsPerCap  5.336445e-01   
72183       72183    World  2016          5001  EFConsTotGHA  3.984702e+09   
72184       72184    World  2016          5001  EFProdPerCap  5.336445e-01   
72185       72185    World  2016          5001  EFProdTotGHA  3.984702e+09   

       grazing_land  forest_land  fishing_ground  built_up_land        carbon  \
0      1.995463e-01  0.097188051    3.688847e-02   2.931995e-02  0.000000e+00   
1      6.870000e+05       334600    1.270000e+05   1.009430e+05  0.000000e+00   
2      1.352610e-01  0.084003213    1.374213e-02   3.339780e-02  0.000000e+00   
3      4.656780e+05  289207.1078    4.731155e+04   1.149823e+05  0.000000e+00   
4      1.894622e-01     1.26E-06    4.164833e-03   3.339780e-02  1.114093e+00   
...             ...          ...             ...            ...           ...   
72181  1.504757e+09  5.11176e+09    1.095445e+09   4.726163e+08  0.000000e+00   
72182  1.402092e-01     0.273495    8.974253e-02   6.329435e-02  1.646235e+00   
72183  1.046937e+09  2.04218e+09    6.701039e+08   4.726163e+08  1.229237e+10   
72184  1.402092e-01     0.273495    8.974253e-02   6.329435e-02  1.646235e+00   
72185  1.046937e+09  2.04218e+09    6.701039e+08   4.726163e+08  1.229237e+10   

              total QScore  
0      5.032351e-01     3A  
1      1.732543e+06     3A  
2      4.262086e-01     3A  
3      1.467355e+06     3A  
4      1.728629e+00     3A  
...             ...    ...  
72181  1.216928e+10     3A  
72182  2.746619e+00     3A  
72183  2.050891e+10     3A  
72184  2.746619e+00     3A  
72185  2.050891e+10     3A  

[72186 rows x 13 columns]

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72186 entries, 0 to 72185
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Unnamed: 0      72186 non-null  int64  
 1   country         72186 non-null  object 
 2   year            72186 non-null  int64  
 3   country_code    72186 non-null  int64  
 4   record          72186 non-null  object 
 5   crop_land       51714 non-null  float64
 6   grazing_land    51714 non-null  float64
 7   forest_land     51714 non-null  object 
 8   fishing_ground  51713 non-null  float64
 9   built_up_land   51713 non-null  float64
 10  carbon          51713 non-null  float64
 11  total           72177 non-null  float64
 12  QScore          72185 non-null  object 
dtypes: float64(6), int64(3), object(4)
memory usage: 7.2+ MB


In [62]:
df.isnull().sum()

Unnamed: 0            0
country               0
year                  0
country_code          0
record                0
crop_land         20472
grazing_land      20472
forest_land       20472
fishing_ground    20473
built_up_land     20473
carbon            20473
total                 9
QScore                1
dtype: int64

In [63]:
# check the output or scores
df['QScore'].value_counts()

3A    51481
2A    10576
2B    10096
1A       16
1B       16
Name: QScore, dtype: int64

In [64]:
# drop null values
df = df.dropna()
df.isna().sum()
df['QScore'].value_counts()

3A    51473
2A      224
1A       16
Name: QScore, dtype: int64

In [65]:
# merge and balance the output samples
df_2A = df[df.QScore=='2A']
df_3A = df[df.QScore=='3A'].sample(350)
data_df = df_2A.append(df_3A)

In [66]:
# shuffle dataset
data_df = sklearn.utils.shuffle(data_df)
data_df = data_df.reset_index(drop=True)
data_df.shape
data_df.QScore.value_counts()

3A    350
2A    224
Name: QScore, dtype: int64

In [67]:
# preprocessing by dropping country codes country and year
data_df = data_df.drop(columns=['country_code', 'country', 'year'])
X = data_df.drop(columns='QScore')
y = data_df['QScore']

In [68]:
# split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)
y_train.value_counts()

3A    255
2A    146
Name: QScore, dtype: int64

In [69]:
encoder = LabelEncoder()
x_train.record = encoder.fit_transform(x_train.record)
x_test.record = encoder.transform(x_test.record)

C:\Users\Praise\anaconda3\lib\site-packages\pandas\core\generic.py:5159: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [70]:
x_test.record

412    3
96     6
478    2
426    3
564    3
      ..
312    1
353    6
285    2
437    0
264    4
Name: record, Length: 173, dtype: int32

In [71]:
# smote training sets
smote = SMOTE(random_state=1)
x_train_balanced, y_balanced = smote.fit_sample(x_train, y_train)

In [72]:
scaler = MinMaxScaler()
normalised_train_df = scaler.fit_transform(
    x_train_balanced.drop(columns=['record']))
normalised_train_df = pd.DataFrame(
    normalised_train_df, columns=x_train_balanced.drop(columns=['record']).columns)
normalised_train_df['record'] = x_train_balanced['record']

x_test = x_test.reset_index(drop=True)
normalised_test_df = scaler.transform(x_test.drop(columns=['record']))
normalised_test_df = pd.DataFrame(
    normalised_test_df, columns=x_test.drop(columns=['record']).columns)
normalised_test_df['record'] = x_test['record']

In [73]:
#Logistic Regression

log_reg = LogisticRegression()
log_reg.fit(normalised_train_df, y_balanced)
#returns
LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)


LogisticRegression()

In [74]:
#  Confusion Matrix
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions = log_reg.predict(normalised_test_df)
cnf_mat = confusion_matrix(
    y_true=y_test, y_pred=new_predictions, labels=['2A', '3A'])
cnf_mat

array([[41, 37],
       [56, 39]], dtype=int64)

In [75]:
# accuracy
accuracy = accuracy_score(y_true=y_test, y_pred=new_predictions)
print('Accuracy: {}'.format(round(accuracy*100), 2))

Accuracy: 46.0


In [76]:
#  Precision
precision = precision_score(y_true=y_test, y_pred=new_predictions, pos_label='2A')
print('Precision: {}'.format(round(precision*100), 2))

Precision: 42.0


In [77]:
#  Recall
recall = recall_score(y_true=y_test, y_pred=new_predictions, pos_label='2A')
print('Recall: {}'.format(round(recall*100), 2))

Recall: 53.0


In [78]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(log_reg, normalised_train_df, y_balanced, cv=5, scoring='f1_macro')
scores

array([0.43983043, 0.52484472, 0.45655333, 0.56034483, 0.43194919])

In [79]:
#  F1-Score
f1 = f1_score(y_true=y_test, y_pred=new_predictions, pos_label='2A')
print('F1: {}'.format(round(f1*100), 2))

F1: 47.0


In [80]:
from sklearn.model_selection import KFold

In [81]:
kf = KFold(n_splits=5)
kf.split(normalised_train_df)
f1_scores = []
# run for every split
for train_index, test_index in kf.split(normalised_train_df):
    x_train, x_test = normalised_train_df.iloc[train_index], normalised_train_df.iloc[test_index]
    y_train, y_test = y_balanced[train_index], y_balanced[test_index]
    model = LogisticRegression().fit(x_train, y_train)
# save result to list
f1_scores.append(
    f1_score(y_true=y_test, y_pred=model.predict(x_test), pos_label='2A')*100)

In [82]:
f1_scores

[0.0]

In [88]:
from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=1)
f1_scores = []
#run for every split
for train_index, test_index in skf.split(normalised_train_df, y_balanced):
  x_train, x_test = np.array(normalised_train_df)[train_index], np.array(normalised_train_df)[test_index]
  y_train, y_test  = y_balanced[train_index], y_balanced[test_index]
  model = LogisticRegression().fit(x_train, y_train)
  #save result to list
  f1_scores.append(f1_score(y_true=y_test, y_pred=model.predict(x_test), pos_label='2A'))


In [89]:
# Leave One Out Cross Validation (LOOCV)
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
scores = cross_val_score(LogisticRegression(), normalised_train_df, y_balanced, cv=loo, 
                         scoring='f1_macro')
average_score = scores.mean() * 100

In [90]:
average_score

50.0

In [91]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier()
dec_tree.fit(normalised_train_df, y_balanced)

DecisionTreeClassifier()

In [112]:
dec_predict = dec_tree.predict_proba(normalised_test_df)
dec_predict

array([[1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.

In [ ]:
# accuracy = accuracy_score(y_true=y_test, y_pred=dec_predict)
# # print('Accuracy: {}'.format(round(accuracy*100), 2))